name: Build CLI

on: 
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Compile
        run: |
          VERSION=$(echo $(date -u; git rev-parse --short HEAD) | sed -e 's/[]$.*[\^]/\\&/g' )
          sed -i "s/%%version%%/${VERSION}/" version.go
          bash build-all.sh
          ls -al bin/

      - name: Push
        run: |
          git config --global user.email "github@scalr.com"
          git config --global user.name "Github Action"
          git add bin/*
          git commit -m "Auto build binaries"
          git push
