name: Build CLI

on: 
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Compile
        run: |
          VERSION="0.$(git rev-list --count HEAD).0"
          echo "version=$VERSION" >> $GITHUB_ENV
          sed -i "s/0.0.0/${VERSION}/" main.go
          bash build-all.sh $VERSION

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ env.version }} --generate-notes ./bin/*.zip ./bin/*_SHA256SUMS
