name: Compile and Release

on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version for new release
        required: true
        default: 0.0.0
        
jobs:
  compile:
    name: Compile and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0  # Required for git operations

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '>=1.18.0'

      - name: Compile and Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ github.event.inputs.version }}"
          stdbuf -oL bash build-all.sh $VERSION
          gh release create v$VERSION --generate-notes ./bin/*.zip ./bin/*_SHA256SUMS
